import { test, expect } from '@playwright/test';

test('completed_todo', async ({ page }) => {
  await page.goto('http://127.0.0.1:5173/course_config/todo');
  await page.getByRole('button', { name: '新增待办' }).click();
  await page.getByText('完整配置').click();
  await page.getByLabel('待办内容：').click();
  await page.getByLabel('待办内容：').fill('测试完成待办逻辑');
  await page.getByLabel('待办类型：').click();
  await page.getByRole('menuitem', { name: '简单分类' }).locator('span').nth(2).click();
  await page.getByRole('menuitem', { name: '简单分类' }).locator('span').nth(2).click();
  await page.getByText('学习成长').click();
  await page.getByRole('menuitem', { name: '记笔记' }).locator('span').nth(2).click();
  await page.getByText('代码世界').click();
  await page.getByRole('menuitem', { name: 'Coding' }).locator('span').nth(2).click();
  await page.locator('div').filter({ hasText: /^记笔记\+ 1$/ }).first().click();
  await page.getByPlaceholder('截止日期').click();
  await page.getByText('19', { exact: true }).click();
  await page.getByPlaceholder('具体时间').click();
  await page.locator('li').filter({ hasText: '00:00' }).click();
  await page.getByRole('button', { name: '提交' }).click();
  await page.getByRole('button', { name: '完成' }).click();
  await page.getByRole('menuitem', { name: '积分记录与兑换' }).click();
  await page.getByText('+6').click();
  await page.getByRole('menuitem', { name: '待办管理' }).click();
  await page.getByRole('button', { name: '新增待办' }).click();
  await page.getByText('完整配置').click();
  await page.getByLabel('待办内容：').click();
  await page.getByLabel('待办内容：').fill('测试过期完成的待办积分');
  await page.getByLabel('待办类型：').click();
  await page.getByText('学习成长').click();
  await page.getByRole('menuitem', { name: '记笔记' }).locator('span').nth(2).click();
  await page.getByRole('menuitem', { name: '视频学习' }).locator('span').nth(2).click();
  await page.getByRole('menuitem', { name: '书籍学习' }).locator('span').nth(2).click();
  await page.locator('div').filter({ hasText: /^记笔记\+ 2$/ }).first().click();
  await page.getByPlaceholder('截止日期').click();
  await page.getByText('17', { exact: true }).click();
  await page.getByPlaceholder('具体时间').click();
  await page.locator('li').filter({ hasText: '01:00' }).click();
  await page.getByRole('button', { name: '提交' }).click();
  await page.getByRole('button', { name: '完成' }).click();
  await page.getByText('积分记录与兑换').click();
  await page.locator('svg').click();
  await page.getByText('+6.5').click();
});